In [68]:
from google.colab import files

uploaded = files.upload()

Saving Superstore.csv to Superstore (2).csv

In [69]:
import pandas as pd

df = pd.read_csv("Superstore.csv", encoding="latin1")

print(df.shape)
df.head()

(9994, 21)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [70]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

In [71]:
df.isnull().sum()

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

In [72]:
df.duplicated().sum()

np.int64(0)

In [73]:
df.dtypes

Row ID             int64
Order ID          object
Order Date        object
Ship Date         object
Ship Mode         object
Customer ID       object
Customer Name     object
Segment           object
Country           object
City              object
State             object
Postal Code        int64
Region            object
Product ID        object
Category          object
Sub-Category      object
Product Name      object
Sales            float64
Quantity           int64
Discount         float64
Profit           float64
dtype: object

In [74]:
df["Order Date"] = pd.to_datetime(df["Order Date"])
df["Ship Date"] = pd.to_datetime(df["Ship Date"])

print(df[["Order Date", "Ship Date"]].dtypes)

Order Date    datetime64[ns]
Ship Date     datetime64[ns]
dtype: object

In [75]:
print("NegativeSales:", (df["Sales"] < 0).sum())
print("NegativeQuantity:", (df["Quantity"] < 0).sum())
print("NegativeProfit:", (df["Profit"] < 0).sum())

NegativeSales: 0
NegativeQuantity: 0
NegativeProfit: 1871

In [76]:
df[["Sales", "Quantity", "Discount", "Profit"]].describe()

              Sales     Quantity     Discount       Profit
count   9994.000000  9994.000000  9994.000000  9994.000000
mean     229.858001     3.789574     0.156203    28.656896
std      623.245101     2.225110     0.206452   234.260108
min        0.444000     1.000000     0.000000 -6599.978000
25%       17.280000     2.000000     0.000000     1.728750
50%       54.490000     3.000000     0.200000     8.666500
75%      209.940000     5.000000     0.200000    29.364000
max    22638.480000    14.000000     0.800000  8399.976000

In [77]:
Q1 = df["Sales"].quantile(0.25)
Q3 = df["Sales"].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

print("Lower Bound:", lower)
print("Upper Bound:", upper)

print("Sales Outliers:",
      ((df["Sales"] < lower) | (df["Sales"] > upper)).sum())

Lower Bound: -271.71000000000004
Upper Bound: 498.93
Sales Outliers: 1167

In [78]:
df[df["Sales"] > 498.93][
    ["Order ID", "Order Date", "Customer ID",
     "Product Name", "Sales", "Quantity", "Profit"]
].sort_values("Sales", ascending=False).head(10)

,Order ID,Order Date,Customer ID,Product Name,Sales,Quantity,Profit
2697,CA-2014-145317,2014-03-18,SM-20320,Cisco TelePresence System EX90 Videoconferenci...,22638.480,6,-1811.0784
6826,CA-2016-118689,2016-10-02,TC-20980,Canon imageCLASS 2200 Advanced Copier,17499.950,5,8399.9760
8153,CA-2017-140151,2017-03-23,RB-19360,Canon imageCLASS 2200 Advanced Copier,13999.960,4,6719.9808
2623,CA-2017-127180,2017-10-22,TA-21385,Canon imageCLASS 2200 Advanced Copier,11199.968,4,3919.9888
4190,CA-2017-166709,2017-11-17,HL-15040,Canon imageCLASS 2200 Advanced Copier,10499.970,3,5039.9856
9039,CA-2016-117121,2016-12-17,AB-10105,GBC Ibimaster 500 Manual ProClick Binding System,9892.740,13,4946.3700
4098,CA-2014-116904,2014-09-23,SC-20095,Ibico EPK-21 Electric Binding System,9449.950,5,4630.4755
4277,US-2016-107440,2016-04-16,BS-11365,"3D Systems Cube Printer, 2nd Generation, Magenta",9099.930,7,2365.9818
8488,CA-2016-158841,2016-02-02,SE-20110,HP Designjet T520 Inkjet Large Format Printer ...,8749.950,5,2799.9840
6425,CA-2016-143714,2016-05-23,CC-12370,Canon imageCLASS 2200 Advanced Copier,8399.976,4,1119.9968

## EDA

In [79]:
print("Total Sales:", df["Sales"].sum())
print("Total Profit:", df["Profit"].sum())
print("Total Quantity:", df["Quantity"].sum())
print("Total Orders:", df["Order ID"].nunique())
print("Total Customers:", df["Customer ID"].nunique())

Total Sales: 2297200.8603000003
Total Profit: 286397.0217
Total Quantity: 37873
Total Orders: 5009
Total Customers: 793

In [80]:
df["Year_Month"] = df["Order Date"].dt.to_period("M")

monthly_sales = (
    df.groupby("Year_Month")["Sales"]
      .sum()
      .reset_index()
)

monthly_sales

   Year_Month        Sales
0     2014-01   14236.8950
1     2014-02    4519.8920
2     2014-03   55691.0090
3     2014-04   28295.3450
4     2014-05   23648.2870
5     2014-06   34595.1276
6     2014-07   33946.3930
7     2014-08   27909.4685
8     2014-09   81777.3508
9     2014-10   31453.3930
10    2014-11   78628.7167
11    2014-12   69545.6205
12    2015-01   18174.0756
13    2015-02   11951.4110
14    2015-03   38726.2520
15    2015-04   34195.2085
16    2015-05   30131.6865
17    2015-06   24797.2920
18    2015-07   28765.3250
19    2015-08   36898.3322
20    2015-09   64595.9180
21    2015-10   31404.9235
22    2015-11   75972.5635
23    2015-12   74919.5212
24    2016-01   18542.4910
25    2016-02   22978.8150
26    2016-03   51715.8750
27    2016-04   38750.0390
28    2016-05   56987.7280
29    2016-06   40344.5340
30    2016-07   39261.9630
31    2016-08   31115.3743
32    2016-09   73410.0249
33    2016-10   59687.7450
34    2016-11   79411.9658
35    2016-12   96999.0430
36    2017-01   43971.3740
37    2017-02   20301.1334
38    2017-03   58872.3528
39    2017-04   36521.5361
40    2017-05   44261.1102
41    2017-06   52981.7257
42    2017-07   45264.4160
43    2017-08   63120.8880
44    2017-09   87866.6520
45    2017-10   77776.9232
46    2017-11  118447.8250
47    2017-12   83829.3188

In [81]:
df["Quarter"] = df["Order Date"].dt.to_period("Q")

quarterly_sales = (
    df.groupby("Quarter")["Sales"]
      .sum()
      .reset_index()
)

quarterly_sales

   Quarter        Sales
0   2014Q1   74447.7960
1   2014Q2   86538.7596
2   2014Q3  143633.2123
3   2014Q4  179627.7302
4   2015Q1   68851.7386
5   2015Q2   89124.1870
6   2015Q3  130259.5752
7   2015Q4  182297.0082
8   2016Q1   93237.1810
9   2016Q2  136082.3010
10  2016Q3  143787.3622
11  2016Q4  236098.7538
12  2017Q1  123144.8602
13  2017Q2  133764.3720
14  2017Q3  196251.9560
15  2017Q4  280054.0670

In [82]:
top_products = (
    df.groupby("Product Name")["Sales"]
      .sum()
      .sort_values(ascending=False)
      .head(10)
      .reset_index()
)

top_products

                                        Product Name      Sales
0              Canon imageCLASS 2200 Advanced Copier  61599.824
1  Fellowes PB500 Electric Punch Plastic Comb Bin...  27453.384
2  Cisco TelePresence System EX90 Videoconferenci...  22638.480
3       HON 5400 Series Task Chairs for Big and Tall  21870.576
4         GBC DocuBind TL300 Electric Binding System  19823.479
5   GBC Ibimaster 500 Manual ProClick Binding System  19024.500
6               Hewlett Packard LaserJet 3310 Copier  18839.686
7  HP Designjet T520 Inkjet Large Format Printer ...  18374.895
8          GBC DocuBind P400 Electric Binding System  17965.068
9        High Speed Automatic Electric Letter Opener  17030.312

In [83]:
region_sales = (
    df.groupby("Region")["Sales"]
      .sum()
      .sort_values(ascending=False)
      .reset_index()
)

region_sales

    Region        Sales
0     West  725457.8245
1     East  678781.2400
2  Central  501239.8908
3    South  391721.9050

In [84]:
monthly_seasonality = (
    df.groupby(df["Order Date"].dt.month)["Sales"]
      .sum()
      .reset_index()
)

monthly_seasonality.columns = ["Month", "Sales"]

monthly_seasonality
monthly_seasonality.sort_values("Sales", ascending=False)

    Month        Sales
10     11  352461.0710
11     12  325293.5035
8       9  307649.9457
2       3  205005.4888
9      10  200322.9847
7       8  159044.0630
4       5  155028.8117
5       6  152718.6793
6       7  147238.0970
3       4  137762.1286
0       1   94924.8356
1       2   59751.2514

### cohort Analysis

In [85]:
df["Purchase_Month"] = df["Order Date"].dt.to_period("M")

In [86]:
df["Cohort_Month"] = (
    df.groupby("Customer ID")["Purchase_Month"]
      .transform("min")
)

In [87]:
df["Cohort_Index"] = (
    (df["Purchase_Month"].dt.year - df["Cohort_Month"].dt.year) * 12
    + (df["Purchase_Month"].dt.month - df["Cohort_Month"].dt.month)
    + 1
)

In [88]:
cohort_data = (
    df.groupby(["Cohort_Month", "Cohort_Index"])["Customer ID"]
      .nunique()
      .reset_index()
)

cohort_data.head(20)

   Cohort_Month  Cohort_Index  Customer ID
0       2014-01             1           32
1       2014-01             2            3
2       2014-01             4            2
3       2014-01             5            2
4       2014-01             7            2
5       2014-01             8            4
6       2014-01             9            5
7       2014-01            10            3
8       2014-01            11            7
9       2014-01            12            5
10      2014-01            13            3
11      2014-01            15            3
12      2014-01            16            3
13      2014-01            17            3
14      2014-01            18            4
15      2014-01            19            3
16      2014-01            20            2
17      2014-01            21            4
18      2014-01            23            6
19      2014-01            24            5

In [89]:
cohort_pivot = cohort_data.pivot(
    index="Cohort_Month",
    columns="Cohort_Index",
    values="Customer ID"
)

cohort_retention = cohort_pivot.div(
    cohort_pivot[1],
    axis=0
) * 100

cohort_retention.round(2)
cohort_retention.round(2).head(10)

Cohort_Index,1,2,3,4,5,6,7,8,9,10,...,39,40,41,42,43,44,45,46,47,48
Cohort_Month,,,,,,,,,,,,,,,,,,,,,
2014-01,100.0,9.38,NaN,6.25,6.25,NaN,6.25,12.50,15.62,9.38,...,18.75,12.50,15.62,12.50,3.12,6.25,28.12,28.12,31.25,18.75
2014-02,100.0,16.67,8.33,4.17,NaN,8.33,8.33,12.50,12.50,16.67,...,8.33,8.33,20.83,12.50,12.50,16.67,25.00,25.00,12.50,NaN
2014-03,100.0,6.15,3.08,12.31,10.77,NaN,10.77,7.69,12.31,9.23,...,20.00,15.38,18.46,9.23,29.23,12.31,27.69,24.62,NaN,NaN
2014-04,100.0,10.71,3.57,7.14,5.36,14.29,10.71,16.07,14.29,1.79,...,8.93,12.50,14.29,26.79,14.29,25.00,25.00,NaN,NaN,NaN
2014-05,100.0,8.93,8.93,7.14,17.86,3.57,21.43,17.86,7.14,5.36,...,12.50,10.71,28.57,12.50,30.36,16.07,NaN,NaN,NaN,NaN
2014-06,100.0,2.08,4.17,8.33,4.17,18.75,16.67,2.08,8.33,12.50,...,6.25,27.08,14.58,29.17,22.92,NaN,NaN,NaN,NaN,NaN
2014-07,100.0,13.64,11.36,NaN,11.36,18.18,4.55,NaN,18.18,4.55,...,25.00,22.73,29.55,20.45,NaN,NaN,NaN,NaN,NaN,NaN
2014-08,100.0,16.33,6.12,22.45,10.20,6.12,8.16,4.08,8.16,6.12,...,24.49,22.45,20.41,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-09,100.0,13.24,13.24,16.18,1.47,2.94,13.24,14.71,13.24,2.94,...,23.53,17.65,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-10,100.0,7.14,11.90,2.38,7.14,9.52,11.90,9.52,7.14,9.52,...,33.33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### RFM SEGMENTATION

In [90]:
analysis_date = df["Order Date"].max() + pd.Timedelta(days=1)

print("Analysis Date:", analysis_date)

Analysis Date: 2017-12-31 00:00:00

In [91]:
rfm = df.groupby("Customer ID").agg({
    "Order Date": lambda x: (analysis_date - x.max()).days,
    "Order ID": "nunique",
    "Sales": "sum"
}).reset_index()

rfm.columns = ["Customer ID", "Recency", "Frequency", "Monetary"]

rfm.head()

  Customer ID  Recency  Frequency  Monetary
0    AA-10315      185          5  5563.560
1    AA-10375       20          9  1056.390
2    AA-10480      260          4  1790.512
3    AA-10645       56          6  5086.935
4    AB-10015      416          3   886.156

In [92]:
rfm.describe()

           Recency   Frequency      Monetary
count   793.000000  793.000000    793.000000
mean    147.802018    6.316520   2896.848500
std     186.211051    2.550885   2628.670117
min       1.000000    1.000000      4.833000
25%      31.000000    5.000000   1146.050000
50%      76.000000    6.000000   2256.394000
75%     184.000000    8.000000   3785.276000
max    1166.000000   17.000000  25043.050000

In [93]:
rfm["R_Score"] = pd.qcut(
    rfm["Recency"].rank(method="first"),
    5,
    labels=[5, 4, 3, 2, 1]
)

rfm["F_Score"] = pd.qcut(
    rfm["Frequency"].rank(method="first"),
    5,
    labels=[1, 2, 3, 4, 5]
)

rfm["M_Score"] = pd.qcut(
    rfm["Monetary"].rank(method="first"),
    5,
    labels=[1, 2, 3, 4, 5]
)
rfm["RFM_Score"] = (
    rfm["R_Score"].astype(int).astype(str) +
    rfm["F_Score"].astype(int).astype(str) +
    rfm["M_Score"].astype(int).astype(str)
)

rfm.head(10)

  Customer ID  Recency  Frequency   Monetary R_Score F_Score M_Score RFM_Score
0    AA-10315      185          5   5563.560       2       2       5       225
1    AA-10375       20          9   1056.390       5       5       2       552
2    AA-10480      260          4   1790.512       1       1       3       113
3    AA-10645       56          6   5086.935       3       3       5       335
4    AB-10015      416          3    886.156       1       1       1       111
5    AB-10060       55          8   7755.620       3       4       5       345
6    AB-10105       42         10  14473.571       4       5       5       455
7    AB-10150       42          5    966.710       4       2       2       422
8    AB-10165       26          8   1113.838       5       4       2       542
9    AB-10255      167          9    914.532       2       5       1       251

In [94]:
def rfm_segment(row):
    r = row["R_Score"]
    f = row["F_Score"]
    m = row["M_Score"]

    if r >= 4 and f >= 4 and m >= 4:
        return "Champions"

    elif r >= 3 and f >= 3:
        return "Loyal Customers"

    elif r >= 4 and f <= 2:
        return "New Customers"

    elif r <= 2 and f >= 3:
        return "At Risk"

    elif r <= 2 and f <= 2 and m <= 2:
        return "Lost"

    else:
        return "Potential Loyalists"


rfm["Segment"] = rfm.apply(rfm_segment, axis=1)

rfm.head(10)

,Customer ID,Recency,Frequency,Monetary,R_Score,F_Score,M_Score,RFM_Score,Segment
0,AA-10315,185,5,5563.560,2,2,5,225,Potential Loyalists
1,AA-10375,20,9,1056.390,5,5,2,552,Loyal Customers
2,AA-10480,260,4,1790.512,1,1,3,113,Potential Loyalists
3,AA-10645,56,6,5086.935,3,3,5,335,Loyal Customers
4,AB-10015,416,3,886.156,1,1,1,111,Lost
5,AB-10060,55,8,7755.620,3,4,5,345,Loyal Customers
6,AB-10105,42,10,14473.571,4,5,5,455,Champions
7,AB-10150,42,5,966.710,4,2,2,422,New Customers
8,AB-10165,26,8,1113.838,5,4,2,542,Loyal Customers
9,AB-10255,167,9,914.532,2,5,1,251,At Risk

In [95]:
segment_summary = (
    rfm["Segment"]
    .value_counts()
    .reset_index()
)

segment_summary.columns = ["Segment", "Customer_Count"]

segment_summary

               Segment  Customer_Count
0      Loyal Customers             224
1              At Risk             146
2                 Lost             117
3  Potential Loyalists             112
4            Champions             106
5        New Customers              88

In [96]:
segment_revenue = (
    rfm.groupby("Segment")["Monetary"]
       .sum()
       .sort_values(ascending=False)
       .reset_index()
)

segment_revenue

               Segment     Monetary
0      Loyal Customers  649620.9361
1            Champions  560498.8171
2              At Risk  497495.9911
3  Potential Loyalists  337263.6317
4        New Customers  159389.4318
5                 Lost   92932.0525

In [97]:
rfm.to_csv("RFM_Segmentation.csv", index=False)

cohort_retention.to_csv("Cohort_Retention.csv")

In [98]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix
)

print("Libraries imported successfully!")

Libraries imported successfully!

In [99]:
cutoff = pd.Timestamp("2017-10-01")

future_end = cutoff + pd.Timedelta(days=90)

print("Historical cutoff:", cutoff.date())
print("Future 90-day end:", future_end.date())

Historical cutoff: 2017-10-01
Future 90-day end: 2017-12-30

In [100]:
# Data before the cutoff
hist = df[df["Order Date"] < cutoff].copy()

# Data in the following 90 days
future = df[
    (df["Order Date"] >= cutoff) &
    (df["Order Date"] <= future_end)
].copy()

# Customer-level historical features
customer_features = hist.groupby("Customer ID").agg(
    Recency=("Order Date", lambda x: (cutoff - x.max()).days),
    Frequency=("Order ID", "nunique"),
    Monetary=("Sales", "sum"),
    Avg_Order_Value=("Sales", "mean"),
    Total_Quantity=("Quantity", "sum")
).reset_index()

print(customer_features.head())
print("Total customers:", len(customer_features))

  Customer ID  Recency  Frequency  Monetary  Avg_Order_Value  Total_Quantity
0    AA-10315       94          5  5563.560       505.778182              30
1    AA-10375       24          8   906.518        75.543167              35
2    AA-10480      169          4  1790.512       149.209333              36
3    AA-10645      392          5  5073.975       298.469118              62
4    AB-10015      325          3   886.156       147.692667              13
Total customers: 790

In [101]:
future_orders = future.groupby("Customer ID")["Order ID"].nunique()

customer_features["Future_Orders_90D"] = (
    customer_features["Customer ID"]
    .map(future_orders)
    .fillna(0)
)

print(customer_features[
    ["Customer ID", "Future_Orders_90D"]
].head(10))

  Customer ID  Future_Orders_90D
0    AA-10315                0.0
1    AA-10375                1.0
2    AA-10480                0.0
3    AA-10645                1.0
4    AB-10015                0.0
5    AB-10060                2.0
6    AB-10105                1.0
7    AB-10150                1.0
8    AB-10165                1.0
9    AB-10255                0.0

In [102]:
customer_features["Churn"] = (
    customer_features["Future_Orders_90D"] == 0
).astype(int)

print(customer_features["Churn"].value_counts())

Churn
0    433
1    357
Name: count, dtype: int64

In [103]:
X = customer_features[
    [
        "Recency",
        "Frequency",
        "Monetary",
        "Avg_Order_Value",
        "Total_Quantity"
    ]
]

y = customer_features["Churn"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Training rows:", len(X_train))
print("Testing rows:", len(X_test))

Training rows: 632
Testing rows: 158

In [104]:
model = DecisionTreeClassifier(
    max_depth=4,
    class_weight="balanced",
    random_state=42
)

model.fit(X_train, y_train)

print("Decision Tree model trained successfully!")

Decision Tree model trained successfully!

In [105]:
y_pred = model.predict(X_test)

print(y_pred[:20])

[1 0 0 0 0 1 0 1 0 0 0 0 0 1 0 0 0 0 0 0]

In [106]:
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, zero_division=0)
recall = recall_score(y_test, y_pred, zero_division=0)
f1 = f1_score(y_test, y_pred, zero_division=0)

print("Accuracy :", round(accuracy * 100, 2), "%")
print("Precision:", round(precision * 100, 2), "%")
print("Recall   :", round(recall * 100, 2), "%")
print("F1 Score :", round(f1 * 100, 2), "%")

Accuracy : 55.06 %
Precision: 50.0 %
Recall   : 23.94 %
F1 Score : 32.38 %

In [107]:
cm = confusion_matrix(y_test, y_pred)

print("Confusion Matrix:")
print(cm)

Confusion Matrix:
[[70 17]
 [54 17]]

In [108]:
customer_features.to_csv(
    "Customer_Churn_Data_Final.csv",
    index=False
)

print("Customer_Churn_Data_Final.csv created successfully!")

Customer_Churn_Data_Final.csv created successfully!